# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b65a513d299e50bfce0d2130c394692f8760e4e982003d97e82f03e61610296d2cef3d81d39c09590a02827b31ebecb011a04b5e8ed78fdccb40869e8099253

test:
  secret_key_base: f3fc0420f6e3500e066be1287dd122c2c90f22e86171668c0d71741ff6f5b61945aa57d39aa9d2b2d813bfbfb7b42be94304a574ab3fe9091ff11c5cec815fe4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
